services:
  gws_mcp:
    build: .
    container_name: gws_mcp
    restart: unless-stopped
    environment:
      - GOOGLE_MCP_CREDENTIALS_DIR=/app/store_creds
    volumes:
      - store_creds:/app/store_creds:rw
    networks:
      - default
      - n8n-docker_default

volumes:
  store_creds:

networks:
  n8n-docker_default:
    external: true
